### ISSUE TITLE
Investigate algolia

### ISSUE THREAD

**Issue by manishas** [Shippable/docs#140]
https://github.com/Shippable/pm/issues/8376

Investigate using https://www.algolia.com/ for docs search results. A lot of companies (including circleci) use them and the free tier is good enough for us.

You can sign up to play around with it, but we need a company account for the actual implementation. Let manishas know and we can create an official company account.

**Comment by ghost** [comment]
Things we need to do to implement search in docs using `Algolia`.

- `Algolia` takes JSON, CSV or TSV format records. So we need a proper structure for the records depending upon what we need to show in the search results to the user and what we need to search for like should it be just the title of the page or everything from the whole content.
![image](https://cloud.githubusercontent.com/assets/19686832/25312837/8105c10c-2840-11e7-9680-a191f54bb98a.png)

- I have taken the below sample structure with `name` and `alternative_name` as the searchable attributes, hence only this values will be searched for on user input.
Sample data that I used.
```JSON
[
  {
    "name": "Getting Started",
    "alternative_name": "What is Shippable",
    "short_data": "Shippable was founded so that software powered organizations could accelerate innovation. We enable this by providing an integrated platform, built from the ground up, to defragment and streamline the process of shipping applications.",
    "link": "http://rcdocs1.shippable.com/"
  },
  {
    "name": "shippable-use-cases",
    "alternative_name": "shippable-use-cases",
    "short_data": "Shippable was founded so that software powered organizations could accelerate innovation. We enable this by providing an integrated platform, built from the ground up, to defragment and streamline the process of shipping applications.",
    "link": "http://rcdocs1.shippable.com/getting-started/shippable-use-cases/"
  },
  {
    "name": "concepts",
    "alternative_name": "shippable-concepts",
    "short_data": "Shippable was founded so that software powered organizations could accelerate innovation. We enable this by providing an integrated platform, built from the ground up, to defragment and streamline the process of shipping applications.",
    "link": "http://rcdocs1.shippable.com/getting-started/shippable-use-cases/"
  }
]
```
`Algolia` searchable attribute settings
![image](https://cloud.githubusercontent.com/assets/19686832/25312844/c3786ae4-2840-11e7-8a12-2a7a3d757769.png)

- We can have `level` as an attribute for Custom Ranking to show the search result like if a user searches for `API` keyword, the main API page should be on the top and detailed API pages after that.
`Algolia` Custom Ranking Attribute
![image](https://cloud.githubusercontent.com/assets/19686832/25313131/1ebd8baa-2846-11e7-8569-282283832d90.png)

- It has `Ranking` and `Typo Tolerance` settings that can show the results even when the user input does not exactly matches with the attribute value.
`Algolia` typo tolerance settings.
![image](https://cloud.githubusercontent.com/assets/19686832/25312880/74b7282c-2841-11e7-93f4-476740387d30.png)

- It has `Synonyms` settings where we can map some user inputs to our attribute value.
![image](https://cloud.githubusercontent.com/assets/19686832/25312888/929a01f2-2841-11e7-8a8a-c008cbf1a1eb.png)

- We can set the maximum number of records to send on a search match so that it does not flood the UI.
![image](https://cloud.githubusercontent.com/assets/19686832/25312893/c726365c-2841-11e7-86a6-6947722384fb.png)

- It has settings for `faceting` the result.
![image](https://cloud.githubusercontent.com/assets/19686832/25313166/2cbdd0c4-2847-11e7-9e7a-0e3e687aadd1.png)

- We can highlight some attributes of the search result.
![image](https://cloud.githubusercontent.com/assets/19686832/25313179/65a82e7a-2847-11e7-8647-ba174193c218.png)
In case of CircleCI.
![image](https://cloud.githubusercontent.com/assets/19686832/25312897/e438971c-2841-11e7-9816-de9c4fe95428.png)

- We can group the search results instead of having all different links.
![image](https://cloud.githubusercontent.com/assets/19686832/25313185/8e373d90-2847-11e7-8485-01da6bfa1ef4.png)

- There are APIs available incase if do not want to change through their UI.
https://www.algolia.com/doc/rest-api/search/
Sample JSON response for search:
```JSON
{
  "hits": [
    {
      "firstname": "Jimmie",
      "lastname": "Barninger",
      "objectID": "433",
      "_highlightResult": {
        "firstname": {
          "value": "<em>Jimmie</em>",
          "matchLevel": "partial"
        },
        "lastname": {
          "value": "Barninger",
          "matchLevel": "none"
        },
        "company": {
          "value": "California <em>Paint</em> & Wlpaper Str",
          "matchLevel": "partial"
        }
      }
    }
  ],
  "page": 0,
  "nbHits": 1,
  "nbPages": 1,
  "hitsPerPage": 20,
  "processingTimeMS": 1,
  "query": "jimmie paint",
  "params": "query=jimmie+paint&attributesToRetrieve=firstname,lastname&hitsPerPage=50"
}
```

To implement I had to add following code:
`shippableDocs` is the index name.
In `main.html`
``` 
<script src="https://cdn.jsdelivr.net/algoliasearch/3/algoliasearch.min.js"></script>
  <script>
    function searchDocs() {
      var searchResults = [];
      var searchInput = document.getElementById("shipDocs-search").value;

      var client = algoliasearch("<application-Id>", '<api-key>');
      var index = client.initIndex('shippableDocs');
      index.search(
        searchInput, {
          hitsPerPage: 5,
          facets: '*',
          maxValuesPerFacet: 10
        },
        searchCallback
      );

      function searchCallback(err, content) {
        if (err) {
          console.error(err);
          return;
        }
        console.log('content', content.hits);
        searchResults = content.hits;
      }
    }
  </script>
```

In `article.html`
```
 <input id="shipDocs-search" type="search" class="shipDocsNav-search-input st-search-input" placeholder="Search..." oninput="searchDocs()">```

**Comment by ghost** [comment]
@manishas Can you have a look on this.

**Comment by ghost** [comment]
- Has been able to create a widget for search with autocomplete and hint options.
![anim](https://cloud.githubusercontent.com/assets/19686832/25334966/83b5a254-290e-11e7-9bef-0bf4ce4b6b1e.gif).

- Need to style it further so that it matches with the current look.
- Need to structure the JSON with things which we want to search for.
 such as fields like `main_section`, `sub_section`, `page_keywords`, `ranking`, `full_content`, `mapping_keywords`,  `page_title`, `page_description` and like wise.

**Comment by ghost** [comment]
Search option now working for the present data.
![image](https://cloud.githubusercontent.com/assets/19686832/25388733/3e0b6dae-29ec-11e7-91ab-e8d36e763342.png)

The current dataset can be checked in algolia dashboard.

**Comment by ghost** [comment]
This is the script that will convert all the docs md files to the json for algolia with keys.
```Javascript
var fs = require('fs');
var glob = require('glob');
var readline = require('readline');
var stream = require('stream');
var _ = require('underscore');
var async = require('async');
var searchJSON = [];
var filePaths = [];
glob("docs/sources/**/*.md", function(err, res) {
  if (err)
    console.log('Error while getting the files');
  filePaths = res;
  async.eachSeries(filePaths,
    function (filePath, callback) {
      var path = filePath;
      var data = {
        page_name: '',
        main_section: '',
        sub_section: '',
        page_title: '',
        page_description: '',
        page_keywords: '',
        page_content: '',
        page_link: ''
      };
      data.page_name = path.replace('docs/sources/', '');
      data.page_name = data.page_name.replace('.md', '');
      data.page_link = 'http://rcdocs1.shippable.com/' + data.page_name;
      var bag = {
        filePath: filePath,
        data: data
      };
      async.series([
          _parseFile.bind(null, bag)
        ],
        function (err) {
          if (err)
            console.log('Error');
          return callback();
        }
      );
    },
    function (err) {
      if (err)
        console.log('failed');
      var json = JSON.stringify(searchJSON);
      console.log(json);
      fs.writeFile('output.json', json);
    }
  );
});

function _parseFile(bag, next) {
  var instream = fs.createReadStream(bag.filePath);
  var outstream = new stream;
  var rl = readline.createInterface(instream, outstream);
  rl.on('line',
    function(line) {
      if (line.indexOf('main_section:') >= 0) {
        var currentLine = line;
        var replacedLine = currentLine.replace('main_section: ', '');
        bag.data.main_section = replacedLine;
      } else if (line.indexOf('sub_section:') >= 0) {
        var currentLine = line;
        var replacedLine = currentLine.replace('sub_section: ', '');
        bag.data.sub_section = replacedLine;
      } else if (line.indexOf('page_title:') >= 0) {
        var currentLine = line;
        var replacedLine = currentLine.replace('page_title: ', '');
        bag.data.page_title = replacedLine;
      } else if (line.indexOf('page_description:') >= 0) {
        var currentLine = line;
        var replacedLine = currentLine.replace('page_description: ', '');
        bag.data.page_description = replacedLine;
      } else if (line.indexOf('page_keywords:') >= 0) {
        var currentLine = line;
        var replacedLine = currentLine.replace('page_keywords: ', '');
        bag.data.page_keywords = replacedLine;
      } else if (line.indexOf('<img') === -1 ) {
        bag.data.page_content +=line;
      }
    }
  )
  .on('close', function () {
    searchJSON.push(bag.data);
    return next();
  });
}
```

**Comment by ghost** [comment]
Integrated algolia with shippable docs
